- menu_name: "Servicios"

- name: "Contáctame"
  url: "/contact/"
  class: "icon-mail"
  title: "¿Quieres contactarme? Hablemos!!"

- name: "Ayudame a mejorar"
  url: "https://github.com/datacubeR/datacubeR.github.io/issues"
  class: "icon-mail"
  title: "Si encuentras un error reportalo en mi Github"

# - name: "RSS"
#   url: "/rss.xml"
#   class: "icon-rss"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   class: "icon-rss"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   class: "icon-magnifying-glass"
#   title: "Sitemap for Google Webmaster Tools"
