- menu_name: "Ayúdame a Mejorar"

- name: "Reporta un Error"
  url: "https://github.com/datacubeR/datacubeR.github.io/issues"
  class: "icon-github"
  title: "Ayúdame a mejorar el contenido, repórtalo en mi Github"

- name: "Contáctame"
  url: "/contact/"
  class: "icon-mail"
  title: "¿Viste algo que debo corregir? Avísame!!"
# - name: "RSS"
#   url: "/rss.xml"
#   class: "icon-rss"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   class: "icon-rss"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   class: "icon-magnifying-glass"
#   title: "Sitemap for Google Webmaster Tools"
